version: '2'
services:
  nest:
    image: lautaroarizmendi/futbol-nest
    volumes:
      - ./:/opt/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=fulbo
      - DB_PASSWORD=del0al9
      - DB_NAME=db_fulbo
    ports:
      - "3000:3000"
      
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes: 
      - './postgres_data:/var/lib/postgresql/data'
    environment: 
      - POSTGRES_USER=fulbo
      - POSTGRES_PASSWORD=del0al9
      - POSTGRES_DB=db_fulbo
    ports: 
      - '5432:5432'