version: '2'
services:   
    postgres:
      image: 'postgres:latest'
      restart: always
      volumes: 
        - './postgres_data:/var/lib/postgresql/data'
      environment: 
        - POSTGRES_USER=fulbo
        - POSTGRES_PASSWORD=del0al9
        - POSTGRES_DB=db_fulbo
      ports: 
        - '5432:5432'